import {
  Body,
  Controller,
  Get,
  Headers,
  Module,
  Post,
  UnauthorizedException,
} from "@nestjs/common";
import {
  ArrayMinSize,
  IsArray,
  IsInt,
  IsIn,
  IsObject,
  IsOptional,
  Matches,
  Min,
  IsString,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { FirebaseDataService } from "../../firebase/firebase-data.service";

type PriorityLevel = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
type DifficultyLevel = "VERY_LOW" | "LOW" | "MEDIUM" | "HIGH" | "VERY_HIGH";

class GptActionTaskDto {
  @IsString()
  title!: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsIn(["LOW", "MEDIUM", "HIGH", "CRITICAL"])
  priority?: PriorityLevel;

  @IsOptional()
  @IsIn(["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"])
  difficulty?: DifficultyLevel;

  @IsOptional()
  @IsInt()
  @Min(5)
  estimatedMinutes?: number;

  @IsOptional()
  @IsString()
  context?: string;

  @IsOptional()
  @IsInt()
  @Min(0)
  scheduledDayOffset?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  dueDayOffset?: number;

  @IsOptional()
  @IsString()
  @Matches(/^([01]\d|2[0-3]):[0-5]\d$/, {
    message: "scheduledTime must use HH:MM 24-hour format",
  })
  scheduledTime?: string;
}

class GptActionRoutineDto {
  @IsString()
  name!: string;

  @IsOptional()
  @IsString()
  @IsIn(["daily", "weekly", "flexible"])
  frequencyType?: string;

  @IsOptional()
  @IsString()
  @IsIn(["morning", "afternoon", "night", "flexible"])
  timePreference?: string;

  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => GptActionTaskDto)
  tasks!: GptActionTaskDto[];
}

class GptActionGoalDto {
  @IsString()
  title!: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsString()
  category?: string;

  @IsOptional()
  @IsIn(["LOW", "MEDIUM", "HIGH", "CRITICAL"])
  priority?: PriorityLevel;
}

class GptActionPlanDto {
  @IsString()
  title!: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsString()
  @IsIn(["daily", "weekly", "biweekly", "monthly"])
  planningHorizon?: string;

  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => GptActionRoutineDto)
  routines!: GptActionRoutineDto[];
}

class GptActionPlanPayloadDto {
  @IsOptional()
  @IsString()
  userId?: string;

  @IsOptional()
  @IsString()
  briefing?: string;

  @IsObject()
  @ValidateNested()
  @Type(() => GptActionGoalDto)
  goal!: GptActionGoalDto;

  @IsObject()
  @ValidateNested()
  @Type(() => GptActionPlanDto)
  plan!: GptActionPlanDto;
}

@Controller("gpt-actions")
class GptActionsController {
  constructor(private readonly database: FirebaseDataService) {}

  private assertActionKey(value?: string) {
    const expected = process.env.HORUS_GPT_ACTION_KEY?.trim();
    if (!expected || value !== expected) {
      throw new UnauthorizedException("Invalid GPT action key");
    }
  }

  private getPublicBaseUrl() {
    return (
      process.env.GPT_ACTIONS_PUBLIC_URL?.replace(/\/$/, "") ||
      process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/, "") ||
      "http://localhost:3001"
    );
  }

  @Get("openapi.json")
  openApiSchema() {
    return {
      openapi: "3.1.0",
      info: {
        title: "Horus Planner GPT Actions",
        version: "1.0.0",
        description:
          "Actions used by a custom ChatGPT/GPT agent to publish structured planning data into Horus Planner.",
      },
      servers: [{ url: this.getPublicBaseUrl() }],
      paths: {
        "/api/gpt-actions/plans": {
          post: {
            operationId: "publishPlanningToHorus",
            summary: "Publish a complete planning structure to Horus Planner",
            description:
              "Creates a goal, plan, routines, tasks and agent session from structured data generated by the GPT.",
            security: [{ HorusActionKey: [] }],
            requestBody: {
              required: true,
              content: {
                "application/json": {
                  schema: { $ref: "#/components/schemas/PlanningPayload" },
                },
              },
            },
            responses: {
              "201": {
                description: "Planning data was accepted and persisted.",
                content: {
                  "application/json": {
                    schema: { $ref: "#/components/schemas/PlanningResult" },
                  },
                },
              },
              "401": { description: "Invalid or missing GPT action key." },
              "400": { description: "Payload validation failed." },
            },
          },
        },
      },
      components: {
        securitySchemes: {
          HorusActionKey: {
            type: "apiKey",
            in: "header",
            name: "x-horus-action-key",
          },
        },
        schemas: {
          PlanningPayload: {
            type: "object",
            additionalProperties: false,
            required: ["goal", "plan"],
            properties: {
              userId: {
                type: "string",
                description:
                  "Optional Horus user id. Omit this to use the default workspace configured in the API.",
              },
              briefing: {
                type: "string",
                description: "Short natural-language summary of the conversation that produced this plan.",
              },
              goal: { $ref: "#/components/schemas/GoalInput" },
              plan: { $ref: "#/components/schemas/PlanInput" },
            },
          },
          GoalInput: {
            type: "object",
            additionalProperties: false,
            required: ["title"],
            properties: {
              title: { type: "string" },
              description: { type: "string" },
              category: { type: "string" },
              priority: {
                type: "string",
                enum: ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
              },
            },
          },
          PlanInput: {
            type: "object",
            additionalProperties: false,
            required: ["title", "routines"],
            properties: {
              title: { type: "string" },
              description: { type: "string" },
              planningHorizon: {
                type: "string",
                enum: ["daily", "weekly", "biweekly", "monthly"],
              },
              routines: {
                type: "array",
                minItems: 1,
                items: { $ref: "#/components/schemas/RoutineInput" },
              },
            },
          },
          RoutineInput: {
            type: "object",
            additionalProperties: false,
            required: ["name", "tasks"],
            properties: {
              name: { type: "string" },
              frequencyType: {
                type: "string",
                enum: ["daily", "weekly", "flexible"],
              },
              timePreference: {
                type: "string",
                enum: ["morning", "afternoon", "night", "flexible"],
              },
              tasks: {
                type: "array",
                minItems: 1,
                items: { $ref: "#/components/schemas/TaskInput" },
              },
            },
          },
          TaskInput: {
            type: "object",
            additionalProperties: false,
            required: ["title"],
            properties: {
              title: { type: "string" },
              description: { type: "string" },
              priority: {
                type: "string",
                enum: ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
              },
              difficulty: {
                type: "string",
                enum: ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
              },
              estimatedMinutes: { type: "integer", minimum: 5 },
              context: { type: "string" },
              scheduledDayOffset: { type: "integer", minimum: 0 },
              dueDayOffset: { type: "integer", minimum: 0 },
              scheduledTime: {
                type: "string",
                description: "Preferred HH:MM time for the task.",
                pattern: "^([01]\\d|2[0-3]):[0-5]\\d$",
              },
            },
          },
          PlanningResult: {
            type: "object",
            properties: {
              ok: { type: "boolean" },
              message: { type: "string" },
              goalId: { type: "string" },
              planId: { type: "string" },
              routinesCreated: { type: "integer" },
              tasksCreated: { type: "integer" },
            },
          },
        },
      },
    };
  }

  @Post("plans")
  async publishPlan(
    @Headers("x-horus-action-key") actionKey: string | undefined,
    @Body() payload: GptActionPlanPayloadDto,
  ) {
    this.assertActionKey(actionKey);
    const userId = await this.database.resolveUserId(undefined, payload.userId);
    const result = await this.database.ingestAgentPlan(userId, payload);

    return {
      ok: true,
      message: `Planejamento "${result.plan.title}" salvo no Horus Planner.`,
      goalId: result.goal.id,
      planId: result.plan.id,
      routinesCreated: result.routines.length,
      tasksCreated: result.tasksCreated,
    };
  }
}

@Module({
  controllers: [GptActionsController],
})
export class GptActionsModule {}
